short_name = "redot"
name = "Redot Engine"
major = 4
minor = 4
patch = 0
status = "dev"
module_config = ""
website = "https://redotengine.org"
docs = "latest"
godot_major = 4
godot_minor = 4
godot_patch = 0
godot_status = "dev"
